### ISSUE TITLE
Sort map keys when spewing

### ISSUE THREAD

**Issue by gbrlsnchs** [bradleyjkemp/cupaloy#56] opened 2019-07-16 03:04 UTC
I'm trying to snapshot a struct whose one of its fields is a map. Sometimes the test passes, at other times it doesn't. Go maps are randomly sorted by default. However, `go-spew` has a [`SortKeys` configuration](https://github.com/davecgh/go-spew#configuration-options) that solves this problem, but it doesn't seem to be used here.

I'm sorry if I'm missing something here, I didn't read the source code so I'm guessing it's a bug and which bug it is, but I might have missed some docs.

Thanks nonetheless!

**Comment by bradleyjkemp** [comment] 2019-07-16 18:22
Hi, you're right this is definitely supposed to work! Both the "SortKeys" and "SpewKeys" options for go-spew are enabled and there's a unit test for a map that I've never yet seen fail for non-deterministic ordering.

Could you give some more details about the type of your map? If you're replying on the "SpewKeys" option then it sounds like your map keys are fairly complex types (which admittedly there's no test coverage for).

**Comment by bradleyjkemp** [comment] 2019-07-24 10:07
@gbrlsnchs I've tried a few different map types but haven't been able to reproduce the issue (even when running the test thousands of times).

Are you able to provide a runnable example which demonstrates your issue?

**Comment by gbrlsnchs** [comment] 2019-07-24 14:34
When I ran into this issue, I was testing a `map[string]*CustomStruct`. Some times the snapshot would fail and some times not, because of the order of elements in the map. I will try again today and let you know if that ever happens again. Thanks!

**Comment by bradleyjkemp** [comment] 2019-08-06 13:03
@gbrlsnchs I've been unable to reproduce this myself so I'm going to close this issue for now.
Please do re-open if you find this still blocks you and we can try to dig in a bit further as to what might be going wrong.

**Closed by bradleyjkemp** 2019-08-06 13:03 UTC
Labels: bug
